plugins {
	id 'java'
	id 'org.springframework.boot' version '3.5.8'
	id 'io.spring.dependency-management' version '1.1.7'
    id "org.liquibase.gradle" version "2.2.2" apply false
}

group = 'com.example'
version = '0.0.1-SNAPSHOT'
description = 'Demo project for Spring Boot'
def jdkVersion = "21"

defaultTasks "bootRun"

jar {
    enabled = false
}

bootJar {
    archiveFileName = String.format("%s-%s.jar", rootProject.name, version)
}

assert System.properties["java.specification.version"] == jdkVersion
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(jdkVersion)
    }
}

repositories {
    mavenCentral()
}

ext {
    springdocVersion = "2.8.11"
    h2Version = "2.4.240"
    //liquibaseVersion = "4.33.0"
    mockitoVersion = "5.19.0"
}

configurations {
     mockitoAgent
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation "org.springdoc:springdoc-openapi-starter-webmvc-ui:${springdocVersion}"

    implementation "org.springframework.boot:spring-boot-starter-data-jpa"
    runtimeOnly "com.h2database:h2:${h2Version}"
    //runtimeOnly "org.liquibase:liquibase-core:${liquibaseVersion}"

    developmentOnly "org.springframework.boot:spring-boot-devtools"

    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'com.google.firebase:firebase-admin:9.3.0'

    testImplementation "org.springframework.boot:spring-boot-starter-test"
    testRuntimeOnly "org.junit.platform:junit-platform-launcher"

    testImplementation "org.mockito:mockito-core:${mockitoVersion}"
    mockitoAgent("org.mockito:mockito-core:${mockitoVersion}") {
        transitive = false
    }
}

tasks.named("test") {
    useJUnitPlatform()
    jvmArgs += "-Xshare:off"
    jvmArgs += "-javaagent:${configurations.mockitoAgent.asPath}"
}

//apply from: "build.migrations.gradle"