spring.application.name=cinema_backend
spring.main.banner-mode=off
logging.level.ru.ulstu.is.server=DEBUG

spring.datasource.url=jdbc:h2:file:./data
spring.datasource.username=sa
spring.datasource.password=sa
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=false


spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
logging.level.org.h2=DEBUG
server.address=0.0.0.0