spring:
    profiles:
        active: dev

server:
    port: 8080

app:
    cinema:
        open-time: "09:00"
        close-time: "23:00"
        cleanup-buffer-minutes: 30
        reservation-timer: 4
        ticket-per-order: 5
        no-refund-before-session: 60
        timezone: Europe/Moscow
