spring:
    profiles:
        active: prod

server:
    address: 0.0.0.0
    port: 8080

app:
    cinema:
        open-time: "09:00"
        close-time: "23:00"
        cleanup-buffer-minutes: 30
        reservation-timer: 1
        ticket-per-order: 5
        no-refund-before-session: 60
        timezone: Europe/Moscow
